Add manual mode to noise reduction + add noise reduction threshold
vircadia/vircadia pull request #1007
Opened 2021-02-09 05:44 UTC by digisomni

I haven't put this into UI yet. I may or may not rename some of these pieces. Also, haven't checked the signals yet.

2021-02-09 07:39 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79_5a400077.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79.tar_5a400077.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79.tar_5a400077.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79_5a400077.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79_5a400077.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-ffd6f79_5a400077.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-ffd6f79_5a400077.apk

2021-02-11 11:22 UTC, digisomni commented
This is ready for review now.

2021-02-11 12:41 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2.tar_97fdd372.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2_97fdd372.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2.tar_97fdd372.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2_97fdd372.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-6bb90c2_97fdd372.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2_97fdd372.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-6bb90c2_97fdd372.exe

2021-02-12 03:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e_799590a0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e.tar_799590a0.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e.tar_799590a0.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e_799590a0.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e_799590a0.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-d429b6e_799590a0.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d429b6e_799590a0.apk

2021-02-12 20:21 UTC, SilverfishVR commented
I seems to work, but I could not find anyone online on master so I did not actually talk to anyone 😄

2021-02-12 20:26 UTC, digisomni commented
> I seems to work, but I could not find anyone online on master so I did not actually talk to anyone 😄

I actually talk to myself, no joke. I'd just listen on my other client to see at what points I'd hear me. :)

2021-02-13 19:35 UTC, ctrlaltdavid commented
UI suggestion: Change "Noise Reduction: Manual/Automatic" to "Manual Noise Reduction".
This would make it clearer that the toggle enables manual noise reduction?

2021-02-13 19:36 UTC, digisomni commented
Currently it's a switch that controls the value of "noiseValueAutomatic" , but I could reverse it and rename it probably, yeah.

2021-02-14 00:08 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9_88b9ebb1.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9.tar_88b9ebb1.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9.tar_88b9ebb1.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9_88b9ebb1.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9_88b9ebb1.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-0dca3d9_88b9ebb1.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-0dca3d9_88b9ebb1.exe

2021-02-23 20:28 UTC, ctrlaltdavid requested changes

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +        if (AudioScriptingInterface.getNoiseReductionThreshold() != sliderValue) {
```suggestion
        if (AudioScriptingInterface.getNoiseReductionThreshold() !== sliderValue) {
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +            width: parent.width - margins.paddings*2;
```suggestion
            width: parent.width - margins.paddings * 2;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                anchors.leftMargin: -size/4; //the glyph has empty space at left about 25%
```suggestion
                anchors.leftMargin: -size / 4; // The glyph has empty space at left about 25%
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        checked = Qt.binding(function() { return AudioScriptingInterface.acousticEchoCancellation; });
```suggestion
                        checked = Qt.binding(function () { return AudioScriptingInterface.acousticEchoCancellation; });
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        checked = Qt.binding(function() { return AudioScriptingInterface.noiseReduction; }); // restore binding
```suggestion
                        checked = Qt.binding(function () { return AudioScriptingInterface.noiseReduction; }); // restore binding
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                    visible: AudioScriptingInterface.noiseReduction === true;
```suggestion
                    visible: AudioScriptingInterface.noiseReduction;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        checked = Qt.binding(function() { return !AudioScriptingInterface.noiseReductionAutomatic; }); // restore binding
```suggestion
                        checked = Qt.binding(function () { return !AudioScriptingInterface.noiseReductionAutomatic; }); // restore binding
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +            width: parent.width - margins.paddings*2;
```suggestion
            width: parent.width - margins.paddings * 2;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +            visible: AudioScriptingInterface.noiseReduction === true && AudioScriptingInterface.noiseReductionAutomatic !== true;
```suggestion
            visible: AudioScriptingInterface.noiseReduction && !AudioScriptingInterface.noiseReductionAutomatic;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        noiseReductionThresholdSlider.value = 0.0
```suggestion
                        noiseReductionThresholdSlider.value = 0.0;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        mouse.accepted = false
```suggestion
                        mouse.accepted = false;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        mouse.accepted = false
```suggestion
                        mouse.accepted = false;
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/audio/Audio.qml
> +                        AudioScriptingInterface.inputLevelChanged.connect(function() { noiseBar.level = AudioScriptingInterface.inputLevel; });
```suggestion
                        AudioScriptingInterface.noiseGateOpened.connect(function () { noiseBar.gated = false; });
                        AudioScriptingInterface.noiseGateClosed.connect(function () { noiseBar.gated = true; });
                        AudioScriptingInterface.inputLevelChanged.connect(function () { noiseBar.level = AudioScriptingInterface.inputLevel; });
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +    Q_PROPERTY(float noiseReductionThreshold READ getNoiseReductionThreshold WRITE setNoiseReductionThreshold NOTIFY noiseReductionThresholdChanged)
JSdoc needs to be added for these new properties.

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +     * Sets the noise gate threshold before your mic audio is transmitted. (Applies only if Audio.noiseReductionAutomatic is off.)
```suggestion
     * Sets the noise gate threshold before your mic audio is transmitted. (Applies only if <code>Audio.noiseReductionAutomatic</code> is <code>false</code>.)
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +     *     This means the mode is set to 'manual'.
```suggestion
     * @param {boolean} isEnabled - <code>true</code> if audio input noise reduction automatic mode is enabled, <code>false</code> if in manual mode.
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +     *     This means the mode is set to 'manual'.
```suggestion
     * @param {boolean} isEnabled - <code>true</code> if audio input noise reduction automatic mode is enabled, <code>false</code> if in manual mode.
```

2021-02-23 20:28 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +     * Triggered when audio input noise reduction threshold is changed.
```suggestion
     * Triggered when the audio input noise reduction threshold is changed.
```

2021-02-24 03:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062.tar_0a6e220c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062_0a6e220c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062.tar_0a6e220c.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062_0a6e220c.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062_0a6e220c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-77dd062_0a6e220c.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-77dd062_0a6e220c.exe

2021-02-24 07:50 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5_83c8b71f.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5.tar_83c8b71f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5_83c8b71f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5.tar_83c8b71f.Z

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-48e03a5_83c8b71f.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5_83c8b71f.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-48e03a5_83c8b71f.exe

2021-02-24 19:48 UTC, ctrlaltdavid requested changes

2021-02-24 19:48 UTC, ctrlaltdavid commented on interface/src/scripting/Audio.h
> +     *     <code>false</code> if in manual mode. Manual mode will allow you to use <code>Audio.noiseReductionAutomatic</code>
```suggestion
     *     <code>false</code> if in manual mode. Manual mode allows you to use <code>Audio.noiseReductionThreshold</code>
```

2021-02-24 22:23 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645_61defe74.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645_61defe74.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645.tar_61defe74.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645.tar_61defe74.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645_61defe74.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-49b8645_61defe74.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-49b8645_61defe74.apk

2021-02-24 22:24 UTC, ctrlaltdavid approved these changes

2021-02-26 04:17 UTC, Aitolda commented
Threshold seems to do what it's supposed to do.. HOWEVER... the "test your mic" audio feed seems to be pre-noise reduction so this is probably not the most ideal place in the signal flow.  Ideally the feed played while you "test your mic| would be after noise reduction.

2021-02-26 06:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e-_520d21b7.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e-.tar_520d21b7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e-.tar_520d21b7.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e-_520d21b7.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e-_520d21b7.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-d8cdc8e_520d21b7.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-d8cdc8e_520d21b7.apk

2021-03-03 09:39 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d-_bc2b3457.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d-.tar_bc2b3457.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d-.tar_bc2b3457.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d-_bc2b3457.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d-_bc2b3457.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-b87126d_bc2b3457.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-b87126d_bc2b3457.apk

2021-03-03 18:05 UTC, Aitolda commented
Mic listen now working post-noise reduction.  Seems to be working as intended.

2021-03-03 18:56 UTC, ctrlaltdavid approved these changes

2021-03-04 02:18 UTC, merged

2021-03-04 03:58 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd-_809bd936.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd-.tar_809bd936.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd-.tar_809bd936.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd-_809bd936.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd-_809bd936.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-Quest-Alpha-PR1007-2f33bcd_809bd936.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1007/Vircadia-PR1007-2f33bcd_809bd936.apk

2021-03-04 04:13 UTC, Aitolda commented
Update tested. Manual noise reduction no longer default (starts automatic). Otherwise continues to function as before.