Add "RELEASE_NAME" to BUILD.md
vircadia/vircadia pull request #1014
Opened 2021-02-10 07:59 UTC by digisomni

2021-02-10 09:53 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a.tar_b995d6d4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a_b995d6d4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a.tar_b995d6d4.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a_b995d6d4.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a_b995d6d4.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-Quest-Alpha-PR1014-578d45a_b995d6d4.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-578d45a_b995d6d4.apk

2021-02-19 20:15 UTC, ctrlaltdavid requested changes

2021-02-19 20:15 UTC, ctrlaltdavid commented on BUILD.md
> +    // The release version. e.g. 2021.3.2
```suggestion
    // The release version, e.g., 2021.3.2.
```

2021-02-19 20:15 UTC, ctrlaltdavid commented on BUILD.md
> +    // The release name. e.g. Eos
```suggestion
    // The release name, e.g., Eos.
```

2021-02-19 20:15 UTC, ctrlaltdavid commented on BUILD.md
> +    // The build commit. e.g. Use a Git hash for the most recent commit in the branch: fd6973b
```suggestion
    // The build commit, e.g., use a Git hash for the most recent commit in the branch - fd6973b.
```

2021-02-21 23:39 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45_e64c9ad0.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45_e64c9ad0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45.tar_e64c9ad0.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45.tar_e64c9ad0.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45_e64c9ad0.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-PR1014-2695e45_e64c9ad0.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1014/Vircadia-Quest-Alpha-PR1014-2695e45_e64c9ad0.apk

2021-02-23 20:06 UTC, ctrlaltdavid approved these changes

2021-02-25 22:31 UTC, merged