Fix profile errors in QML. (also add FIXME's)
vircadia/vircadia pull request #1017
Opened 2021-02-10 11:58 UTC by digisomni

Any ideas on exactly what profiles were doing/how they were used? https://github.com/vircadia/vircadia/pull/988/files is where I made changes to it originally, I'm not entirely sure what the use of profiles are without an interceptor being needed to add to the user agent.

I checked the history on the CTRL+B browser and it does not persist (as is expected), so I'm not entirely sure....

Was it that profiles are used to pass it on to new browser instances? But if that's the case, then can the webengine actually modify them? Is it needed to be an alias all the way down? Why not copy it from the bottom up one way?

2021-02-10 13:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9_65bef5d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9.tar_65bef5d3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9.tar_65bef5d3.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9_65bef5d3.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9_65bef5d3.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-8615fd9_65bef5d3.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-Quest-Alpha-PR1017-8615fd9_65bef5d3.apk

2021-02-10 20:31 UTC, ctrlaltdavid requested changes
In addition to these fixes, I suggest reinstating commented out versions of the `webViewCoreProfile` lines removed in the original PR988.
I.e., add the following line:
```
    //property alias webViewCoreProfile: webViewCore.profile
```
To each of these QML files:
- controls/+webengine/FlickableWebViewCore.qml
- controls/FlickableWebViewCore.qml
Along with FIXME comments for each saying why these lines need to be disabled in order for the Web user agent feature to work.

2021-02-10 20:32 UTC, ctrlaltdavid commented
### Testing

QA testing should include:
- Check that HTML apps including the following work: Snap, People, Explore, Emote, Appreciate, More, Create
	Test desktop (toolbar mode) and VR (tablet mode).
- Check that the built-in Web browser (Ctrl-B to display) works, including back, forward, reload, and pop-out.
- Web entity user agent editing per https://github.com/vircadia/vircadia/pull/988.

2021-02-10 21:20 UTC, digisomni commented
I'll check that stuff in the resulting generated PR build.

2021-02-10 21:27 UTC, ctrlaltdavid approved these changes

2021-02-10 23:11 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8.tar_dfa9b552.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8_dfa9b552.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8.tar_dfa9b552.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8_dfa9b552.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-Quest-Alpha-PR1017-28e3cd8_dfa9b552.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8_dfa9b552.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1017/Vircadia-PR1017-28e3cd8_dfa9b552.exe

2021-02-11 01:37 UTC, digisomni commented
OK, so everything seems to be working now according to that test plan.

2021-02-11 02:23 UTC, merged