Create App FEB2021 bundle
vircadia/vircadia pull request #1030
Opened 2021-02-12 05:09 UTC by AleziaKurdis

This PR contains:

**Menu reorganization**
EntityList menubar has been reorganized, introducing a new menu “**Transform**”
The menu items has been re-dispatched. CSS has been retouched to display clearly which menu is open.

![image](https://user-images.githubusercontent.com/60075796/107732378-3432c900-6cc6-11eb-95da-2ab204bf6936.png)

**New optional full path & file name URL column in the EntityList**
A new optional column “URL” has been added (hidden by default) to the EntityList. (Issue #977)
It displays the full URL including the path. The column is sortable. It is also searchable, but only if visible.

![image](https://user-images.githubusercontent.com/60075796/107732512-8c69cb00-6cc6-11eb-8f4c-da1d541ca159.png)

2021-02-12 07:00 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0.tar_6ffb8485.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0.tar_6ffb8485.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0_6ffb8485.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0_6ffb8485.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0_6ffb8485.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-Quest-Alpha-PR1030-fc857d0_6ffb8485.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-fc857d0_6ffb8485.apk

2021-02-15 21:34 UTC, Aitolda commented
Working.  No complaints.  Just used it very quickly to sort through a domain to make sure all my models were on my S3.  Also transform menu elements are working as expected.

2021-02-17 00:52 UTC, ctrlaltdavid requested changes

2021-02-17 00:52 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/js/entityList.js
> +
Unnecessary whitespace.

2021-02-17 00:52 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/js/entityList.js
> +                                                                 columnsByID["urlWithPath"].elTh.style.visibility === "visible")||
```suggestion
                                                                 columnsByID["urlWithPath"].elTh.style.visibility === "visible") ||
```

2021-02-17 04:42 UTC, ctrlaltdavid approved these changes

2021-02-17 06:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c_b2b38ad2.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c.tar_b2b38ad2.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c_b2b38ad2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c.tar_b2b38ad2.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c_b2b38ad2.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c_b2b38ad2.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-Quest-Alpha-PR1030-d150b9c_b2b38ad2.apk

2021-02-17 21:06 UTC, SilverfishVR commented
testing [Vircadia-PR1030-d150b9c](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1030/Vircadia-PR1030-d150b9c_b2b38ad2.exel)

tested mostly in VR, works well and all menu's fit in tablet 👍

2021-02-17 21:09 UTC, merged