Add ability to preload entity script whitelist
vircadia/vircadia pull request #1082
Opened 2021-03-08 07:05 UTC by digisomni

I also renamed the "INITIAL_STARTUP_LOCATION" to "PRELOADED_STARTUP_LOCATION".

To test this feature, you have to have the environment variable set when CMake is run. The whitelist should then be activated and also be prepopulated with the values that you had set.

2021-03-08 08:56 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef-.tar_b5d89c44.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef-.tar_b5d89c44.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef-_b5d89c44.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef-_b5d89c44.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef-_b5d89c44.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-4f972ef_b5d89c44.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-Quest-Alpha-PR1082-4f972ef_b5d89c44.apk

2021-03-09 21:32 UTC, ctrlaltdavid requested changes

2021-03-09 21:32 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptGatekeeper.cpp
> +    if (_initialized == true) {
```suggestion
    if (_initialized) {
```

2021-03-09 21:32 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptGatekeeper.cpp
> +    Setting::Handle<bool> whitelistEnabled{ SCRIPT_WHITELIST_ENABLED_KEY, false };
```suggestion
    Setting::Handle<bool> whitelistEnabled { SCRIPT_WHITELIST_ENABLED_KEY, false };
```

2021-03-09 21:32 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptGatekeeper.cpp
> +        qDebug() << "hi" << !whitelistEnabled.get() << whitelistEnabled.get();
Remove debug?

2021-03-09 21:32 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptGatekeeper.h
> +    bool _initialized{ false };
```suggestion
    bool _initialized { false };
```

2021-03-11 20:04 UTC, ctrlaltdavid approved these changes

2021-03-11 23:04 UTC, Aitolda commented
Seems to be working per verbal instructions by Kalila.

2021-03-11 23:05 UTC, merged

2021-03-12 00:29 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00-.tar_d8a3d56d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00-.tar_d8a3d56d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00-_d8a3d56d.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00-_d8a3d56d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00-_d8a3d56d.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-Quest-Alpha-PR1082-72dda00_d8a3d56d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1082/Vircadia-PR1082-72dda00_d8a3d56d.apk