Implement Linux machine fingerprints
vircadia/vircadia pull request #1092
Opened 2021-03-14 00:14 UTC by daleglass

We do this by using either /etc/machine-id, or hashing the MACs of all
non-virtual networking devices.

We make this fingerpint unique to our platform by adding our own string
to the hash, and add some stretching for good measure. This way Vircadia's
fingerprint isn't going to match the system's ID or anything another
application generates.

2021-03-14 02:05 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe-_9f1581a9.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe-.tar_9f1581a9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe-.tar_9f1581a9.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe-_9f1581a9.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe-_9f1581a9.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-Quest-Alpha-PR1092-41370fe_9f1581a9.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-41370fe_9f1581a9.apk

2021-03-14 08:09 UTC, ctrlaltdavid requested changes

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +    QCryptographicHash hash{QCryptographicHash::Keccak_256};
```suggestion
    QCryptographicHash hash(QCryptographicHash::Keccak_256);
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +    QFile machineIdFile{"/etc/machine-id"};
```suggestion
    QFile machineIdFile("/etc/machine-id");
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +        QDir netDevicesDir{"/sys/class/net"};
```suggestion
        QDir netDevicesDir("/sys/class/net");
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +        if ( netDevicesInfo.empty() ) {
```suggestion
        if (netDevicesInfo.empty()) {
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +        for( auto& fileInfo : netDevicesInfo ) {
```suggestion
        for (auto& fileInfo : netDevicesInfo) {
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +    for(int i=0;i<65535;i++) {
```suggestion
    for (int i=0; i<65535; i++) {
```

2021-03-14 08:09 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +    result.resize(128/8); // GUIDs are 128 bit numbers
```suggestion
    result.resize(128 / 8); // GUIDs are 128 bit numbers
```

2021-03-14 13:16 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331-_5345ba27.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331-.tar_5345ba27.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331-.tar_5345ba27.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331-_5345ba27.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331-_5345ba27.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-Quest-Alpha-PR1092-fd08331_5345ba27.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-fd08331_5345ba27.apk

2021-03-14 20:11 UTC, ctrlaltdavid requested changes

2021-03-14 20:11 UTC, ctrlaltdavid commented on libraries/networking/src/FingerprintUtils.cpp
> +    for (int i=0; i<65535; i++) {
```suggestion
    for (int i=0; i < 65535; i++) {
```

2021-03-14 20:19 UTC, ctrlaltdavid approved these changes

2021-03-14 21:53 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1-_1ed767df.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1-.tar_1ed767df.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1-.tar_1ed767df.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1-_1ed767df.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1_1ed767df.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-Quest-Alpha-PR1092-91df8b1_1ed767df.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1092/Vircadia-PR1092-91df8b1-_1ed767df.exe

2021-03-18 21:13 UTC, digisomni commented
To test: Please run Interface multiple times and ensure your fingerprint stays the same.
You can check your fingerprint with the domain-server panel, or search the log.

2021-03-20 14:05 UTC, JulianGro commented
On my machine where `/etc/machine-id` is a things, the fingerprint stays the same.

2021-03-20 18:16 UTC, merged