Rename fbx to model serializers
vircadia/vircadia pull request #1178
Opened 2021-04-15 18:24 UTC by JulianGro

This PR moves all model serializers from the `fbx` folder to the `model-serializers` folder.
I guess High Fidelity was just always too lazy to clean this up. It seem somewhat important to do this cleanup though, as a new developer would hardly be searching for the gltf or obj serializers in the "fbx" folder.

2021-04-15 18:42 UTC, HifiExperiments requested changes
I think it’s a good idea to have these changes in their own PR, separate from the general serializer overhaul.  just a few comments

2021-04-15 18:42 UTC, HifiExperiments commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                           QVector<L>& outarray, int accessorType) {
this looks like we’ve lost some stuff here

2021-04-15 18:42 UTC, HifiExperiments commented on libraries/model-serializers/src/GLTFSerializer.h
> +    bool normalized{ false };
put back space

2021-04-15 19:42 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-8568400-_8573425f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-8568400-.tar_8573425f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-8568400-.tar_8573425f.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-8568400-_8573425f.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-8568400-_8573425f.exe

2021-04-15 20:44 UTC, ctrlaltdavid commented
Android build failed with a cmake error: https://github.com/vircadia/vircadia/runs/2355646699

2021-04-15 21:53 UTC, JulianGro commented
Sorry about the mess. Half of that was a GitAhead bug and the other half was me somehow ending up with an outdated GLTFSerializer.

2021-04-15 23:30 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a-.tar_f6d9cd6f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a-_f6d9cd6f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a-.tar_f6d9cd6f.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a-_f6d9cd6f.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a-_f6d9cd6f.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-PR1178-78e791a_f6d9cd6f.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1178/Vircadia-Quest-Alpha-PR1178-78e791a_f6d9cd6f.apk

2021-04-16 00:04 UTC, HifiExperiments approved these changes

2021-04-16 00:06 UTC, digisomni commented
A good test would be to just run this on Windows and see if everything works as usual.

2021-04-19 20:00 UTC, digisomni approved these changes
Works fine for me on Windows.

2021-04-19 20:00 UTC, merged