Add Doxygen tool for compiling C++ documentation
vircadia/vircadia pull request #1212
Opened 2021-05-11 23:10 UTC by ctrlaltdavid

See /tools/doxygen/README.md for usage instructions.

- It is configured to generate documentation only for items that actually have documentation. (There is a little documentation in the codebase already.)
- This C++ documentation is separate from the scripting API documentation, which is also generated from the C++ code using JSDoc.
- In order to prevent the C++ and scripting API documentation source from clashing, all occurrences of the `/**jsdoc` JSDoc tag have been changed to `/*@jsdoc`.

2021-05-13 20:50 UTC, digisomni requested changes

2021-05-13 20:50 UTC, digisomni commented on tools/doxygen/README.md
> +- [Doxygen Web Site](https://www.doxygen.nl/)
```suggestion
- [Doxygen Website](https://www.doxygen.nl/)
```

2021-05-13 20:50 UTC, digisomni commented on tools/doxygen/Doxyfile
> +PROJECT_LOGO           = D:/Workspaces/CtrlAltStudio/Vircadia-A/Vircadia-A/tools/doxygen/vircadia.png
```suggestion
PROJECT_LOGO           = vircadia.png
```

2021-05-14 04:28 UTC, digisomni approved these changes

2021-05-14 04:29 UTC, merged

2021-05-14 04:54 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-Interface-PR1212-dfea9d8-_f3ee99fe.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-dfea9d8-.tar_f3ee99fe.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-dfea9d8-_f3ee99fe.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-dfea9d8-.tar_f3ee99fe.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-dfea9d8-_f3ee99fe.dmg

2021-05-14 06:21 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-7e31bd7-_27779030.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-7e31bd7-.tar_27779030.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-7e31bd7-.tar_27779030.gz

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-Interface-PR1212-7e31bd7-_27779030.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-7e31bd7-_27779030.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1212/Vircadia-PR1212-7e31bd7-_27779030.exe