Update MacOS packaging instructions.
vircadia/vircadia pull request #1227
Opened 2021-05-26 00:23 UTC by digisomni

2021-05-26 02:25 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-Interface-PR1227-40dcb90-_06b09dab.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90-.tar_06b09dab.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90-.tar_06b09dab.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90-_06b09dab.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90-_06b09dab.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90-_06b09dab.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-40dcb90_06b09dab.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-Quest-Alpha-PR1227-40dcb90_06b09dab.apk

2021-06-01 08:29 UTC, ctrlaltdavid requested changes

2021-06-01 08:29 UTC, ctrlaltdavid commented on INSTALLER.md
> +#### Option A: Use GUI
```suggestion
#### Option A: Use XCode
```
Presumably the GUI to use is XCode?

2021-06-01 17:58 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-Interface-PR1227-99fabea-_6ce944ab.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea-.tar_6ce944ab.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea-.tar_6ce944ab.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea-_6ce944ab.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea-_6ce944ab.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea_6ce944ab.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-Quest-Alpha-PR1227-99fabea_6ce944ab.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1227/Vircadia-PR1227-99fabea-_6ce944ab.exe

2021-06-03 21:27 UTC, ctrlaltdavid approved these changes

2021-06-03 21:27 UTC, merged