Add basic MSIX instructions to INSTALLER.md.
vircadia/vircadia pull request #1245
Opened 2021-06-16 04:24 UTC by digisomni

These will be revised at a later date with corrections and/or specifics as I run through the process more times.

2021-06-16 06:15 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-Interface-PR1245-c547d93-_7bbce4a0.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-PR1245-c547d93-_7bbce4a0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-PR1245-c547d93-.tar_7bbce4a0.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-PR1245-c547d93-.tar_7bbce4a0.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-PR1245-c547d93-_7bbce4a0.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-PR1245-c547d93_7bbce4a0.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1245/Vircadia-Quest-Alpha-PR1245-c547d93_7bbce4a0.apk

2021-06-17 21:06 UTC, ctrlaltdavid requested changes

2021-06-17 21:06 UTC, ctrlaltdavid commented on INSTALLER.md
> +#### Create an MSIX Package
```suggestion
#### Create an MSIX Package for the Windows Store
```

2021-06-17 21:31 UTC, ctrlaltdavid approved these changes

2021-06-17 23:34 UTC, merged