Update user docs links "docs.vircadia.dev" -> "docs.vircadia.com".
vircadia/vircadia pull request #1249
Opened 2021-06-21 16:07 UTC by digisomni

I don't think this would need much in the way of testing in the native Interface itself, however any and all testing is welcome!

2021-06-21 17:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-Interface-PR1249-d3db480-_d26e0357.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480-.tar_d26e0357.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480-_d26e0357.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480-.tar_d26e0357.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480-_d26e0357.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480_d26e0357.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-Quest-Alpha-PR1249-d3db480_d26e0357.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-d3db480-_d26e0357.exe

2021-06-26 23:26 UTC, ctrlaltdavid requested changes

2021-06-26 23:26 UTC, ctrlaltdavid commented on server-console/src/content-update.html
> +        <h3>We backed up your old Server content, just in case.</h3>
```suggestion
        <h3>We backed up your old server content, just in case.</h3>
```

2021-06-26 23:26 UTC, ctrlaltdavid commented on server-console/src/content-update.html
> +                        <p><b>1.</b> Stop your Vircadia server.
```suggestion
                        <p><b>1.</b> Stop your Vircadia Server.
```

2021-06-26 23:26 UTC, ctrlaltdavid commented on server-console/src/content-update.html
> +                      <p><b>4.</b> Restart your Vircadia server.
```suggestion
                      <p><b>4.</b> Restart your Vircadia Server.
```

2021-06-27 09:48 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-Interface-PR1249-018f02f-_a32dc628.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f-_a32dc628.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f-.tar_a32dc628.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f-_a32dc628.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f-.tar_a32dc628.Z

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-Quest-Alpha-PR1249-018f02f_a32dc628.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f_a32dc628.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1249/Vircadia-PR1249-018f02f-_a32dc628.exe

2021-06-27 09:50 UTC, ctrlaltdavid approved these changes

2021-06-27 09:55 UTC, merged