Archive cmake logs, for debugging
vircadia/vircadia pull request #1274
Opened 2021-07-03 23:42 UTC by daleglass

2021-07-04 01:37 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-54bc61a-.tar_3ce06318.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-54bc61a-_3ce06318.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-54bc61a-.tar_3ce06318.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-54bc61a-_3ce06318.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-Quest-Alpha-PR1274-54bc61a_3ce06318.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-54bc61a_3ce06318.apk

2021-07-04 12:48 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-b53d35a-.tar_4558be24.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-b53d35a-_4558be24.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-b53d35a-.tar_4558be24.gz

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-Quest-Alpha-PR1274-b53d35a_4558be24.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-b53d35a_4558be24.apk

2021-07-04 18:45 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-1b0e3f3-.tar_54b28a1f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-1b0e3f3-.tar_54b28a1f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-1b0e3f3-_54b28a1f.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-1b0e3f3-_54b28a1f.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-1b0e3f3_54b28a1f.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-Quest-Alpha-PR1274-1b0e3f3_54b28a1f.apk

2021-07-04 18:46 UTC, daleglass commented
Okay, this seems to be in order now. This collects and archives vcpkg logs as artifacts.

2021-07-06 20:38 UTC, JulianGro requested changes
The archive should really be added to the vircadia-build-notifier so people can actually take a look at what went wrong themselves.

2021-07-06 21:28 UTC, digisomni commented
Is this based on an old branch because MacOS doesn't appear to build.

2021-07-06 21:31 UTC, daleglass commented
@JulianGro Hmm, how? I'm new at this GHA stuff.

@digisomni Yes, this was made inspired by the trouble with the nvtt change, and tested precisely against that problem. I intentionally left it that way, rather than rebasing after we fixed that.

2021-07-06 21:36 UTC, ctrlaltdavid commented
A rebuild will pick up the latest fixes in `master`.

2021-07-06 21:39 UTC, JulianGro commented
Oh. You are uploading the files beforehand instead of using the Upload Artifact job. My understanding is that a server behind the Upload Artifact job posts all these files, so you will either need to do the same thing as in Upload Artifact or have Upload Artifact upload the CMake logs.

2021-07-06 23:28 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963-_54b28a1f.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963-.tar_54b28a1f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963-.tar_54b28a1f.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963-_54b28a1f.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-Interface-PR1274-57d1963-_54b28a1f.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963_54b28a1f.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-Quest-Alpha-PR1274-57d1963_54b28a1f.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1274/Vircadia-PR1274-57d1963-_54b28a1f.exe

2021-07-08 20:06 UTC, daleglass commented
@JulianGro I don't quite understand? I'm using `actions/upload-artifact@v2`. It seems to upload fine.

2021-07-08 23:05 UTC, JulianGro commented
> @JulianGro I don't quite understand? I'm using `actions/upload-artifact@v2`. It seems to upload fine.

Yes. You use `actions/upload-artifact@v2` while the rest of the stuff uses a job called "Upload Artifact" which just runs `$PYTHON_EXEC "$GITHUB_WORKSPACE/tools/ci-scripts/upload_to_publish_server.py"`

2021-07-08 23:09 UTC, daleglass commented
Yes, I'm not sure the script would be appropriate as-is anyway. This is for debugging, there's no need to prominently post build logs.

The artifacts can be found in the build logs, in the "Artifacts" button above the log output:
https://github.com/vircadia/vircadia/pull/1274/checks?check_run_id=2983930580

2021-07-08 23:21 UTC, JulianGro commented
Oh I didn't know that. For some reason I assumed they were uploaded to the S3.

2021-07-08 23:25 UTC, JulianGro commented
Wasn't the plan to upload all the vcpkg logs as well? `Vircadia/vcpkg/*/buildtrees/*/*.log`
I assumed you were doing this to help with the case of something like nvtt not building anymore. I don't see how the currently uploaded logs help with that.

2021-07-10 18:45 UTC, daleglass commented
> Wasn't the plan to upload all the vcpkg logs as well? `Vircadia/vcpkg/*/buildtrees/*/*.log`
> I assumed you were doing this to help with the case of something like nvtt not building anymore. I don't see how the currently uploaded logs help with that.

It should be doing that, actually.

2021-07-10 23:41 UTC, JulianGro commented
Yeah it got some on MacOS.
I cannot find any on my Linux build VM, so I must assume that vcpkg only saves logs if something actually fails.

2021-07-10 23:42 UTC, daleglass commented
That's what it looks like to me too

2021-07-10 23:42 UTC, JulianGro approved these changes

2021-07-15 21:08 UTC, merged