Remove snaps in goto & nearby teleport references
vircadia/vircadia pull request #1298
Opened 2021-07-25 23:28 UTC by digisomni

This addresses #1021 in that the Pal's text was not updated to reflect the change.

Another PR should be opened later to perhaps come up with a better way to indicate someone is not available or have it go from Interface -> Domain -> Other Person's Interface instead of (I believe) traversing the Metaverse.

The need to have people be able to effortlessly teleport and follow people around as newbies is a priority. We should come up with a good privacy indicator/function for within domains that doesn't affect this in any substantial way.

P.S. didn't mean to open this branch in the main repo, GitHub web editor, amirite?

2021-07-26 01:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-Interface-PR1298-becaa21-_facee334.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-becaa21-_facee334.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-becaa21-_facee334.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-becaa21-.tar_facee334.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-becaa21-.tar_facee334.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-becaa21-_facee334.exe

2021-07-29 21:21 UTC, ctrlaltdavid approved these changes

2021-07-29 21:21 UTC, daleglass approved these changes

2021-07-29 21:23 UTC, daleglass requested changes
This change leaves some strings ending with a `,`

2021-07-29 21:25 UTC, ctrlaltdavid requested changes

2021-07-29 21:25 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/Pal.qml
> +                        "You will appear offline in the 'Connections' list,"],
```suggestion
                        ["Your username will be visible in everyone's 'Nearby' list.",
                        "Your location will be visible in the 'Connections' list only for those with whom you are connected or friends. They'll be able to jump to your location if the domain allows.",
                        "Your location will be visible in the 'Connections' list only for those with whom you are friends. They'll be able to jump to your location if the domain allows.",
                        "You will appear offline in the 'Connections' list."],
```

2021-08-07 19:56 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-336ba38-_3f1c7fae.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-Interface-PR1298-336ba38-_3f1c7fae.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-336ba38-.tar_3f1c7fae.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-336ba38-.tar_3f1c7fae.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-336ba38-_3f1c7fae.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-336ba38-_3f1c7fae.exe

2021-08-08 22:57 UTC, ctrlaltdavid approved these changes

2021-08-19 23:30 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-c33b2ad-.tar_3f1c7fae.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-c33b2ad-_3f1c7fae.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-c33b2ad-.tar_3f1c7fae.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-c33b2ad-_3f1c7fae.exe

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-Interface-PR1298-c33b2ad-_3f1c7fae.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-c33b2ad-_3f1c7fae.dmg

2021-08-20 06:01 UTC, digisomni commented
It works correctly in testing. However, now the menu has whitespace at the bottom due to the smaller button sizes.

2022-01-24 23:23 UTC, digisomni commented
This PR will be updated by Namark to fix the spacing then it should be good to review and test once more before merging.

2022-02-11 20:16 UTC, namark commented
Couldn't quite figure out how to make it sized based on content, so just eyeballed it.

2022-02-11 22:03 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-Interface-PR1298-89d4163-_f9eb292e.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-_f9eb292e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-.tar_f9eb292e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-.tar_f9eb292e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-_f9eb292e.sh

2022-02-11 22:26 UTC, namark approved these changes

2022-02-12 18:50 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-Interface-PR1298-89d4163-_f9eb292e.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-_f9eb292e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-.tar_f9eb292e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-.tar_f9eb292e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-_f9eb292e.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1298/Vircadia-PR1298-89d4163-_f9eb292e.exe

2022-02-26 19:10 UTC, merged