Assignment client WebRTC connections
vircadia/vircadia pull request #1313
Opened 2021-08-18 09:57 UTC by ctrlaltdavid

- Web SDK connections to assignment clients: Individual WebRTC data channel connections to each assignment client, with WebRTC signaling routed via the domain server.
- Protocol change: New "WebRTC signaling" packet used by the domain server and assignment clients to exchange Web SDK to/from assignment client signaling messages.
- ...

2021-08-18 11:52 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8f9e51c-.tar_ace612d0.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8f9e51c-_ace612d0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8f9e51c-.tar_ace612d0.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8f9e51c-_ace612d0.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-Interface-PR1313-8f9e51c-_ace612d0.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8f9e51c-_ace612d0.exe

2021-08-21 11:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-a6ad75f-.tar_16050399.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-a6ad75f-_16050399.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-a6ad75f-.tar_16050399.Z

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-Interface-PR1313-a6ad75f-_16050399.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-a6ad75f-_16050399.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-a6ad75f-_16050399.exe

2021-08-28 18:04 UTC, daleglass requested changes

2021-08-28 18:04 UTC, daleglass commented on domain-server/src/DomainServer.cpp
> +    if (!destinationNode) {
No errror message here either

2021-08-29 03:50 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-Interface-PR1313-8998de0-_adc94a28.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8998de0-_adc94a28.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8998de0-_adc94a28.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8998de0-.tar_adc94a28.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8998de0-.tar_adc94a28.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1313/Vircadia-PR1313-8998de0-_adc94a28.exe

2021-08-30 20:37 UTC, ctrlaltdavid commented on assignment-client/src/AssignmentClient.cpp
> +        if (!json.keys().contains("to") || !json.keys().contains("from")) {
The echo functionality is just an internal test/debugging feature and not used in Interface per se, so any echo error doesn't need surfacing on the user client.

"To" and "from" are used for relaying signaling messages between the user client and each of the domain server and assignment clients. In one

2021-08-31 22:46 UTC, daleglass approved these changes

2021-08-31 23:16 UTC, digisomni approved these changes
Works fine in conjunction with the Web SDK PR25 test suite.

2021-08-31 23:17 UTC, merged