make HUD bubble/shield button optional
vircadia/vircadia pull request #1314
Opened 2021-08-18 20:24 UTC by SilverfishVR

Adds an menu item in "Settings" to toggle the HUD shield/bubble button on or off.
Shield button remains available in the tablet or toolbar, it is called "HUD shield button" but suggestions are welcome

fixes https://github.com/vircadia/vircadia/issues/1210 but makes it optional.

2021-08-21 09:39 UTC, ctrlaltdavid requested changes
Just a couple of minor items.

2021-08-21 09:39 UTC, ctrlaltdavid commented on scripts/system/bubble.js
> +            AvatarInputs.setShowBubbleTools(Menu.isOptionChecked(menuItem))
```suggestion
            AvatarInputs.setShowBubbleTools(Menu.isOptionChecked(menuItem));
```

2021-08-21 09:39 UTC, ctrlaltdavid commented on scripts/system/bubble.js
> +        if (menuItem == menuItemName) {
```suggestion
        if (menuItem === menuItemName) {
```

2021-08-21 18:35 UTC, ctrlaltdavid approved these changes

2021-08-21 20:27 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-Interface-PR1314-f821989-_a7dee4bb.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-f821989-.tar_a7dee4bb.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-f821989-_a7dee4bb.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-f821989-.tar_a7dee4bb.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-f821989-_a7dee4bb.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-f821989-_a7dee4bb.exe

2021-08-21 21:30 UTC, digisomni commented on scripts/system/bubble.js
> +    var menuItemName = "HUD shield button";
```suggestion
    var menuItemName = "HUD Shield Button";
```

2021-08-21 21:30 UTC, digisomni commented
Works fine, just that one change and I think it'll be good to go.

2021-08-22 09:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-49b9154-_4d21cedf.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-49b9154-.tar_4d21cedf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-49b9154-.tar_4d21cedf.Z

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-Interface-PR1314-49b9154-_4d21cedf.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-49b9154-_4d21cedf.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1314/Vircadia-PR1314-49b9154-_4d21cedf.exe

2021-08-22 20:34 UTC, digisomni approved these changes

2021-08-22 20:35 UTC, merged