Remove second argument from some playSystemSound() calls.
vircadia/vircadia pull request #1473
Opened 2021-11-24 17:04 UTC by Penguin-Guru

I'm not really sure how this was working before but the comments suggest this was the initial intention and it seems to work fine for me. May or may not fix https://github.com/vircadia/vircadia/issues/1453.

2021-11-24 19:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-_65dcd583.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-.tar_65dcd583.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-.tar_65dcd583.Z

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-Interface-PR1473-597df36-_65dcd583.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-_65dcd583.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-_65dcd583.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-_65dcd583.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-.tar_65dcd583.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-597df36-.tar_65dcd583.Z

2021-11-25 00:20 UTC, ctrlaltdavid commented
The second, position parameter was removed from `playSystemSound()` in commit `fa08e42`.

In addition to the changes made. the `qmlPosition` property should be marked as "deprecated" in the JSDoc in MyAvatar.h.

2021-11-25 01:57 UTC, Penguin-Guru commented
Is that good?

2021-11-25 06:00 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-Interface-PR1473-7afe1d8-_78981307.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-_78981307.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-.tar_78981307.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-.tar_78981307.Z

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-_78981307.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-_78981307.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-_78981307.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-.tar_78981307.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-.tar_78981307.Z

2021-11-25 22:40 UTC, ctrlaltdavid requested changes
Looking good. Just a doc change to make.

2021-11-25 22:40 UTC, ctrlaltdavid commented on interface/src/avatar/MyAvatar.h
> +     * @property {Vec3} qmlPosition - A synonym for <code>position</code> for use by QML. This is deprecated.
```suggestion
     * @property {Vec3} qmlPosition - A synonym for <code>position</code> for use by QML.
     *     <p class="important">Deprecated: This property is deprecated and will be removed.</p>
```

2021-11-26 07:22 UTC, ctrlaltdavid commented
QA: Check that the "TEST YOUR SOUND" button works in Settings > Audio... dialog, both desktop and VR tabs.

2021-11-26 07:23 UTC, ctrlaltdavid approved these changes

2021-12-10 03:35 UTC, AleziaKurdis commented
Tested with the Windows build: https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1473/Vircadia-PR1473-7afe1d8-_78981307.exe

Covered:
Audio app: "Test your Sound" button.

I have not too much idea of what is the Simplify UI. so that part has not been tested. (but according the code change... It would be surprising that this wouldn't work too.)

2021-12-11 19:58 UTC, merged