Explicitly encode QStrings to utf8
vircadia/vircadia pull request #1485
Opened 2021-11-28 21:26 UTC by daleglass

Fixes some warnings. Shouldn't make any functional difference.

2021-11-28 23:28 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-_28add85c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-.tar_28add85c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-_28add85c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-.tar_28add85c.gz

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-Interface-PR1485-0711a3f-_28add85c.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-_28add85c.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-.tar_28add85c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-.tar_28add85c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-0711a3f-_28add85c.sh

2021-11-29 19:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-.tar_8c60ba65.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-_8c60ba65.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-.tar_8c60ba65.Z

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-_8c60ba65.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-Interface-PR1485-fabed6b-_8c60ba65.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-.tar_8c60ba65.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-.tar_8c60ba65.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-_8c60ba65.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-fabed6b-_8c60ba65.exe

2021-12-23 08:55 UTC, ctrlaltdavid requested changes

2021-12-23 08:55 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append(QString("scope=%1").arg(ACCOUNT_MANAGER_REQUESTED_SCOPE).toUtf8());
Simpler change...
```
postData.append("scope=" + ACCOUNT_MANAGER_REQUESTED_SCOPE.toUtf8());
```
No warnings on Windows.

2021-12-23 08:55 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append(QByteArray("redirect_uri=") + QUrl::toPercentEncoding(redirectUri));
Simpler...
```
    postData.append("client_id=" + clientId.toUtf8() + "&");
    postData.append("client_secret=" + clientSecret.toUtf8() + "&");
    postData.append("code=" + authCode.toUtf8() + "&");
    postData.append("redirect_uri=" + QUrl::toPercentEncoding(redirectUri));
    ```
No warnings on Windows.

2021-12-23 08:55 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append(QString("scope=%1").arg(ACCOUNT_MANAGER_REQUESTED_SCOPE).toUtf8());
Similarly here and elsewhere in this PR.

2022-01-02 21:10 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-Interface-PR1485-52c758c-_33bf554b.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-_33bf554b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-.tar_33bf554b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-_33bf554b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-.tar_33bf554b.Z

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-.tar_33bf554b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-_33bf554b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-52c758c-.tar_33bf554b.Z

2022-01-04 02:05 UTC, ctrlaltdavid requested changes

2022-01-04 02:05 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append(QByteArray("redirect_uri=") + QUrl::toPercentEncoding(redirectUri));
```suggestion
    postData.append("redirect_uri=" + QUrl::toPercentEncoding(redirectUri));
```

2022-01-04 02:05 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append(QByteArray("steam_auth_ticket=") + QUrl::toPercentEncoding(authSessionTicket) + "&");
```suggestion
    postData.append("steam_auth_ticket=" + QUrl::toPercentEncoding(authSessionTicket) + "&");
```

2022-01-04 02:05 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +    postData.append("scope=" +  ACCOUNT_MANAGER_REQUESTED_SCOPE.toUtf8());
```suggestion
    postData.append("scope=" + ACCOUNT_MANAGER_REQUESTED_SCOPE.toUtf8());
```

2022-01-04 02:05 UTC, ctrlaltdavid commented on libraries/networking/src/AccountManager.cpp
> +        postData.append(QByteArray("refresh_token=") + QUrl::toPercentEncoding(_accountInfo.getAccessToken().refreshToken) + "&");
```suggestion
        postData.append("refresh_token=" + QUrl::toPercentEncoding(_accountInfo.getAccessToken().refreshToken) + "&");
```

2022-01-04 02:05 UTC, ctrlaltdavid commented on libraries/networking/src/DomainAccountManager.cpp
> +    formData.append(QString("client_id=%1").arg(_currentAuth.clientID).toUtf8());
```suggestion
    formData.append("username=" + QUrl::toPercentEncoding(username) + "&");
    formData.append("password=" + QUrl::toPercentEncoding(password) + "&");
    formData.append("client_id=" + _currentAuth.clientID.toUtf8());
```

2022-01-17 00:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-Interface-PR1485-3d4163c-_309e2b0e.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-_309e2b0e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-.tar_309e2b0e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-.tar_309e2b0e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-_309e2b0e.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-_309e2b0e.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-_309e2b0e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-.tar_309e2b0e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1485/Vircadia-PR1485-3d4163c-.tar_309e2b0e.gz

2022-01-17 20:20 UTC, ctrlaltdavid approved these changes

2022-01-20 21:46 UTC, digisomni approved these changes
Seems to work fine for me on Windows, tested logins on serverless, a server, and a localhost server.

2022-01-20 22:04 UTC, merged