Remove deprecated usage of setUserData
vircadia/vircadia pull request #1502
Opened 2021-11-29 22:00 UTC by daleglass

This removes the usage of QObjectUserData, setUserData and userData.

The actual change is minor but this required rearranging things a bit. MenuUserData class is now declared in the header so that the Q_OBJECT macro is processed properly.

Fixes #1305

2021-11-30 00:05 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-Interface-PR1502-3e52320-_a0ba2911.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-3e52320-.tar_a0ba2911.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-3e52320-.tar_a0ba2911.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-3e52320-_a0ba2911.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-3e52320-_a0ba2911.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-3e52320-_a0ba2911.exe

2021-12-04 19:24 UTC, digisomni commented
Needs testing by someone in VR. :)

2022-01-08 18:49 UTC, ksuprynowicz commented
I just tested it in VR, especially with the tablet. Works perfectly fine.

2022-01-08 19:27 UTC, digisomni commented
This should be ready for review after 1485 is merged.

2022-01-16 22:49 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-Interface-PR1502-a06dffd-_b8045b01.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-_b8045b01.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-.tar_b8045b01.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-_b8045b01.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-.tar_b8045b01.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-_b8045b01.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-.tar_b8045b01.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-.tar_b8045b01.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-a06dffd-_b8045b01.sh

2022-01-17 20:31 UTC, ctrlaltdavid requested changes
Needs updating with PR #1485 changes once that PR is merged.

2022-01-17 20:31 UTC, ctrlaltdavid commented on libraries/ui/src/VrMenu.cpp
> +                {
```suggestion
                if (dpc->propertyName() == "exclusionGroup") {
```

2022-01-20 22:09 UTC, ctrlaltdavid approved these changes

2022-01-21 02:01 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-Interface-PR1502-d08156b-_27ddd1d6.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-.tar_27ddd1d6.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-.tar_27ddd1d6.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-_27ddd1d6.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-_27ddd1d6.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-_27ddd1d6.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-.tar_27ddd1d6.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-_27ddd1d6.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1502/Vircadia-PR1502-d08156b-.tar_27ddd1d6.gz

2022-01-22 19:16 UTC, merged