Changes to for loops needed to prevent crash on some GLTF models
vircadia/vircadia pull request #1545
Opened 2021-12-20 00:13 UTC by ksuprynowicz

Fixes https://github.com/vircadia/vircadia/issues/1542

2021-12-20 05:15 UTC, HifiExperiments approved these changes

2021-12-20 09:03 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-Interface-PR1545-ab98c02-_9a3a22d3.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-_9a3a22d3.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-_9a3a22d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-.tar_9a3a22d3.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-.tar_9a3a22d3.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-_9a3a22d3.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-_9a3a22d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-.tar_9a3a22d3.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-ab98c02-.tar_9a3a22d3.Z

2021-12-20 09:53 UTC, ctrlaltdavid requested changes

2021-12-20 09:53 UTC, ctrlaltdavid commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                for (int n = 0; n + 2 < vertices.size(); n = n + verticesStride) {
```suggestion
                for (int n = 0; n + verticesStride - 1 < vertices.size(); n = n + verticesStride) {
```

2021-12-20 09:53 UTC, ctrlaltdavid commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                for (int n = 0; n + 2 < normals.size(); n = n + normalStride) {
```suggestion
                for (int n = 0; n + normalStride - 1 < normals.size(); n = n + normalStride) {
```

2021-12-20 19:17 UTC, ctrlaltdavid approved these changes

2021-12-20 22:40 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-_a7883fc5.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-Interface-PR1545-c946cf2-_a7883fc5.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-.tar_a7883fc5.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-.tar_a7883fc5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-_a7883fc5.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-_a7883fc5.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-.tar_a7883fc5.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-_a7883fc5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1545/Vircadia-PR1545-c946cf2-.tar_a7883fc5.Z

2021-12-22 00:00 UTC, Aitolda commented
Do you have any of the models that were causing the crash for testing?

2021-12-22 05:40 UTC, ksuprynowicz commented
> Do you have any of the models that were causing the crash for testing?
Here's the link to them:
https://drive.google.com/file/d/1fkCb173ts0QlMuZjtMTdJpr0rHIKqQ51/view?usp=sharing
One of them is immediately crashing current release.

2021-12-22 19:49 UTC, ksuprynowicz commented
I tested it on Linux, and it fixed the bug. This PR works fine and on the same world current master branch crashes immediately.

2021-12-23 19:15 UTC, Aitolda commented
> Here's the link to them:
https://drive.google.com/file/d/1fkCb173ts0QlMuZjtMTdJpr0rHIKqQ51/view?usp=sharing
One of them is immediately crashing current release

2021-12-23 19:20 UTC, Aitolda commented
I could not reproduce the crash on the current version using Windows 10 with any of the models  with either the current version (Selene) OR this PR. However, I went to various domains and had no issues with models that weren't already present with Selene, so it doesn't appear to have broken anything either.  Perhaps this bug is unique to Linux?

2021-12-23 22:13 UTC, merged