Improvements in sign-up UX
vircadia/vircadia pull request #1580
Opened 2022-01-24 21:32 UTC by namark

If email confirmation is required a popup is shown instead of
attempting to login immediately,
Various Metaverse server API error cases handled and reported/logged.

Supersedes https://github.com/vircadia/vircadia/pull/1566

2022-01-25 06:46 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-Interface-PR1580-3ac7fb9-_a22a93d8.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-3ac7fb9-_a22a93d8.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-3ac7fb9-.tar_a22a93d8.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-3ac7fb9-.tar_a22a93d8.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-3ac7fb9-_a22a93d8.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-3ac7fb9-_a22a93d8.exe

2022-01-27 23:07 UTC, digisomni requested changes

2022-01-28 09:26 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-.tar_ca6be915.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-.tar_ca6be915.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-_ca6be915.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-_ca6be915.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-Interface-PR1580-98c8611-_ca6be915.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-_ca6be915.exe

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-_ca6be915.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-.tar_ca6be915.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1580/Vircadia-PR1580-98c8611-.tar_ca6be915.gz

2022-01-29 19:03 UTC, daleglass approved these changes

2022-01-29 21:06 UTC, digisomni approved these changes
Works fine for me on Windows.

2022-01-29 21:06 UTC, merged