Fix/update references
vircadia/vircadia pull request #906
Opened 2020-12-11 00:00 UTC by digisomni

Updates license headers and updates references to 'kasenvr' repo to 'vircadia' repo.

2020-12-13 08:04 UTC, ctrlaltdavid requested changes

2020-12-13 08:04 UTC, ctrlaltdavid commented on BUILD_ANDROID.md
> +`git clone https://github.com/vircadia/project-athena.git`
```suggestion
`git clone https://github.com/vircadia/vircadia.git`
```
And elsewhere.

2020-12-13 09:25 UTC, ctrlaltdavid commented on BUILD_ANDROID.md
> +`git clone https://github.com/vircadia/project-athena.git`
There are other occurrences, too.

2020-12-13 19:28 UTC, ctrlaltdavid requested changes

2020-12-13 19:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
> +            text: "<a href=\"https://github.com/vircadia/project-athena\">Vircadia Github</a>."
```suggestion
            text: "<a href=\"https://github.com/vircadia/vircadia\">Vircadia Github</a>."
```

2020-12-13 19:28 UTC, ctrlaltdavid commented on interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
> +                About.openUrl("https:/github.com/vircadia/project-athena");
```suggestion
                About.openUrl("https:/github.com/vircadia/vircadia");
```

2020-12-14 04:16 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-2185fc0.tar_1634138c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-2185fc0_1634138c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-2185fc0.tar_1634138c.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-2185fc0_1634138c.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Quest-Alpha-PR906-2185fc0_1634138c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-2185fc0_1634138c.apk

2020-12-14 06:35 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5_261c2e6c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5_261c2e6c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5.tar_261c2e6c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5.tar_261c2e6c.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5_261c2e6c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Quest-Alpha-PR906-301cee5_261c2e6c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR906/Vircadia-Alpha-PR906-301cee5_261c2e6c.apk

2020-12-15 03:33 UTC, ctrlaltdavid approved these changes

2020-12-15 06:29 UTC, merged