Create app dec2020 material icons
vircadia/vircadia pull request #907
Opened 2020-12-11 03:03 UTC by AleziaKurdis

**Material icons in edit mode**

1- This adds a new **Material icon** to identify the material entities that are linked to a parent.
Since those material entities become invisible, this helps to figure their presence.

![image](https://user-images.githubusercontent.com/60075796/101855885-3d6eb080-3b32-11eb-9a9c-18e8cad7ebe7.png)

2- The Create App - Preference: "**Show Zones in Create Mode**"
has been removed, since it was doing nothing for a couple of years now.
the method behind is still in the API, but do nothing. 
(abandoned since it was only drawing a box that wasn't useful to figure the shape of the zone)
There was no real value to bring this back in a different way.

3- The Create App - Preference: "**Show Lights and Particle Systems in Create Mode**"
has been **renamed** for "**Show Icons in Create Mode**"
since this setting was also managing all the icons (including Zones and now the Parented Materials)
The objective of the setting is mainly to simplify the display at the edit when a scene is very dense.
(In the future, we might want to make this "à la carte". For now, I think we can try as is. )

4- **3dImage Overlays** used for the **icons** has been migrated to **Local Entities**.

5- All the **Entities icons** (in-world non physical entitities) has been updated to be more **uniformized**. They are now **all with the same dark gray tone**, **with a white border** to keep them visible under different lighting.

2020-12-12 20:47 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-35e3e9f.tar_28e53c9c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-35e3e9f.tar_28e53c9c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-35e3e9f_28e53c9c.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-35e3e9f_28e53c9c.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-35e3e9f_28e53c9c.exe

2020-12-17 10:33 UTC, ctrlaltdavid requested changes

2020-12-17 10:33 UTC, ctrlaltdavid commented on scripts/system/libraries/entityIconOverlayManager.js
> +            },"local");
```suggestion
            overlay = Entities.addEntity({
                type: "Image", 
                billboardMode: "full", 
                emissive: true
            }, "local");
```

2020-12-18 04:58 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c.tar_7ff8236d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c.tar_7ff8236d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c_7ff8236d.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c_7ff8236d.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c_7ff8236d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Quest-Alpha-PR907-e9d219c_7ff8236d.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR907/Vircadia-Alpha-PR907-e9d219c_7ff8236d.exe

2020-12-20 00:18 UTC, ctrlaltdavid approved these changes

2020-12-23 21:08 UTC, SilverfishVR commented
Looks good to me 👍 
Thank you, I've been wanting this since I started using material entities 😃

2020-12-24 17:59 UTC, Aitolda commented
Seems to be working as intended.

2020-12-24 22:24 UTC, merged