Add Tips for making pull request to CONTRIBUTING.md
vircadia/vircadia pull request #916
Opened 2020-12-14 02:51 UTC by vegaslon

Add a few pointer to make it easier to get a PR through for the next guy.

2020-12-14 22:09 UTC, JulianGro requested changes
I cannot give suggestions for line 10, 51 and 52 via GitHub for some reason, but one might as well go the extra mile to get those up to date.

2020-12-14 22:09 UTC, JulianGro commented on CONTRIBUTING.md
>    git remote add upstream https://github.com/kasenvr/project-athena
```suggestion
  git remote add upstream https://github.com/vircadia/vircadia
```

2020-12-14 22:09 UTC, JulianGro commented on CONTRIBUTING.md
> +2. [Add](https://github.com/kasenvr/project-athena/issues/new) your request to the issues list!
```suggestion
2. [Add](https://github.com/vircadia/vircadia/issues/new) your request to the issues list!
```

2020-12-14 22:16 UTC, JulianGro approved these changes
Actually all those outdated links are changed in PR #908 , so this is fine if it gets rebased after #908 gets merged

2020-12-14 22:48 UTC, digisomni requested changes

2020-12-14 22:48 UTC, digisomni commented on CONTRIBUTING.md
> +4. If accessing any external service make note of how to get a basic setup for these services or what they are based on.
```suggestion
1. Have a basic description in your pull request. 
2. Write a basic test plan if you are altering or adding features.
3. If a new API is added, try to make sure that some level of basic documentation on how you can utilize it is included.
4. If an added API or feature requires an external service, try to document or link to instructions on how to create a basic working setup.
```

2020-12-14 22:50 UTC, digisomni commented
There are other open references PRs that will update references such as links to the repo.

2020-12-16 22:55 UTC, daleglass approved these changes

2020-12-16 23:01 UTC, digisomni requested changes
Just the one last thing but otherwise looks good. :)

2020-12-16 23:01 UTC, digisomni commented on CONTRIBUTING.md
> +
```suggestion
```

Was this on purpose?

2020-12-17 01:37 UTC, digisomni approved these changes

2020-12-17 01:37 UTC, merged