Skip repeated log entries
vircadia/vircadia pull request #937
Opened 2020-12-27 21:38 UTC by daleglass

This helps with log flooding. Successive repeated log messages will be skipped and counted, the count will be output when a different message is logged.    

A new option of 'keep_repeats' has been added to `VIRCADIA_LOG_OPTIONS` to disable this.

Fixes #934

2020-12-27 22:43 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-788184b.tar_6de94c44.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-788184b_6de94c44.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-788184b.tar_6de94c44.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-788184b_6de94c44.dmg

2021-01-04 20:17 UTC, ctrlaltdavid requested changes

2021-01-04 20:17 UTC, ctrlaltdavid commented on libraries/shared/src/LogHandler.cpp
> +        if ( _repeatCount > 0 ) {
```suggestion
    if (_keepRepeats || _previousMessage != message) {
        if (_repeatCount > 0) {
```

2021-01-04 20:17 UTC, ctrlaltdavid commented on libraries/shared/src/LogHandler.h
> +    int _repeatCount{ 0 };
```suggestion
    bool _keepRepeats { false };

    QString _previousMessage;
    int _repeatCount { 0 };
```

2021-01-05 01:16 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc_189b4baa.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc.tar_189b4baa.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc.tar_189b4baa.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc_189b4baa.dmg

2021-01-05 19:15 UTC, ctrlaltdavid approved these changes

2021-01-05 20:29 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc_189b4baa.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc_189b4baa.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc.tar_189b4baa.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-8c252fc.tar_189b4baa.Z

2021-01-09 20:44 UTC, vircadia-build-notifier commented
The following links are available: 
**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Quest-Alpha-PR937-10307e9_aab5b22e.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.apk

2021-01-14 23:35 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9.tar_aab5b22e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9.tar_aab5b22e.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.exe

2021-01-15 03:59 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9.tar_aab5b22e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9.tar_aab5b22e.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR937/Vircadia-Alpha-PR937-10307e9_aab5b22e.exe

2021-01-15 20:12 UTC, ctrlaltdavid approved these changes

2021-01-16 08:51 UTC, digisomni commented
Is there a specific type of log message that I can trigger in order to test this? I used it for a few minutes but didn't really notice anything different even when I did see what looked like "repeated" log entries.

2021-01-16 18:10 UTC, SilverfishVR commented
https://github.com/vircadia/vircadia/pull/474 was implemented specifically to address missing joint log spam, that would be redundant now right?

2021-01-16 18:56 UTC, daleglass commented
@digisomni Use Developer/Audio/Stats on Linux. If you don't have a Verdana font, you'll get around 150 messages per second

@SilverfishVR Possibly, not. This PR only happens the case when a message is repeated right after itself. From what I remember from looking at the other mechanism it's subsystem specific and may work better for that case because for instance you can avoid repeats within a subsystem even if something else logs stuff in between.

2021-01-21 21:06 UTC, digisomni commented
In LogHandler.cpp on line 142 it appears there is functionality for this sort of thing already. Can this be updated to work with/improve that functionality? I found this because I noticed my log was blocking repeated messages from another part of the codebase already.

2021-01-23 23:02 UTC, digisomni commented
Tested on Mac, there were no font issues so I could not reproduce and trigger this.

2021-01-28 22:22 UTC, merged