Cmake: build in build dir
vircadia/vircadia pull request #943
Opened 2020-12-29 00:18 UTC by daleglass

This makes it so that resources and jsdoc are generated directly into the build directory.

After this PR, the only generated file in the source dir that remains is `tools/jsdoc/package-lock.json`, which might be correct (it says it should go in the source tree) and should be harmless.

2020-12-29 01:19 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-f761e20.tar_d848d082.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-f761e20.tar_d848d082.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-f761e20_d848d082.sh

2021-01-04 20:09 UTC, ctrlaltdavid requested changes

2021-01-04 20:09 UTC, ctrlaltdavid commented on hifi_qt.py
> +        print("You'll need to install the development packages, and to have Qt 5.15.0 or newer. ")
```suggestion
        print("You'll need to install the development packages, and to have Qt 5.15.0 or later. ")
```
Perhaps.

2021-01-04 20:09 UTC, ctrlaltdavid commented on tools/jsdoc/plugins/hifiJSONExport.js
> +            if ( argv[i] == '-d' && i <= argv.length+1) {
```suggestion
        for (var i=0; i < argv.length; i++) {
            if (argv[i] === '-d') {
```
` i <= argv.length + 1` will always be `true`.

2021-01-05 01:22 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-2f0c304.tar_e66f24d6.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-2f0c304.tar_e66f24d6.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Alpha-PR943-2f0c304_e66f24d6.sh

2021-01-19 07:39 UTC, HifiExperiments commented
does this address https://github.com/vircadia/vircadia/issues/670

2021-02-16 19:43 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff.tar_f2932e65.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff.tar_f2932e65.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Quest-Alpha-PR943-f15f1ff_f2932e65.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.apk

2021-02-17 22:58 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff.tar_f2932e65.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff.tar_f2932e65.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Quest-Alpha-PR943-f15f1ff_f2932e65.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-f15f1ff_f2932e65.apk

2021-02-26 19:52 UTC, ctrlaltdavid commented
OSX build is failing with the following:
```
/usr/local/Cellar/cmake/3.19.4/bin/cmake -E copy_directory /Users/runner/work/vircadia/build/interface/tools/jsdoc /Users/runner/work/vircadia/build/interface/Release/interface.app/Contents/MacOS/../Resources/jsdoc
Error copying directory from "/Users/runner/work/vircadia/build/interface/tools/jsdoc" to "/Users/runner/work/vircadia/build/interface/Release/interface.app/Contents/MacOS/../Resources/jsdoc".
make: *** [interface_buildpart_0] Error 1
Command /bin/sh failed with exit code 2
** BUILD FAILED **
```

2021-06-27 15:08 UTC, daleglass commented
Okay, this should be functional now!

2021-06-27 16:43 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-748b33e-.tar_7cb8c535.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-748b33e-.tar_7cb8c535.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-748b33e-_7cb8c535.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-748b33e_7cb8c535.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Quest-Alpha-PR943-748b33e_7cb8c535.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-748b33e-_7cb8c535.exe

2021-06-29 20:37 UTC, ctrlaltdavid requested changes

2021-06-29 20:37 UTC, ctrlaltdavid commented on tools/jsdoc/plugins/hifiJSONExport.js
> +        for(var i=0; i<argv.length; i++) {
```suggestion
        for (var i = 0; i < argv.length; i++) {
```

2021-07-01 18:34 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-7ffe519-.tar_41924980.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-7ffe519-_41924980.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-7ffe519-.tar_41924980.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-7ffe519-_41924980.exe

2021-07-02 01:22 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-2733165-_c3f649a5.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Interface-PR943-2733165-_c3f649a5.dmg

2021-07-04 00:03 UTC, sethalves commented
```
cd /home/seth/src/vircadia/build/interface && /usr/local/bin/cmake -E copy_if_different /home/seth/src/vircadia/interface/resources/serverless/redirect.json /home/seth/src/vircadia/build/interface/resources/serverless/redirect.json
cd /home/seth/src/vircadia/build/interface && /usr/local/bin/cmake -E copy_directory  /home/seth/src/vircadia/build/interface/jsdoc
CMake Error: cmake version 3.21.0-rc2
Usage: /usr/local/bin/cmake -E <command> [arguments...]
```

2021-07-04 00:05 UTC, daleglass commented
@sethalves That's a new one, could you post a full log somewhere, including any cmake arguments?

2021-07-04 01:28 UTC, sethalves commented
I will post a log, but I think it's probably the same thing that the autobuilder is hitting:

https://github.com/vircadia/vircadia/pull/943/checks?check_run_id=2979649796

2021-07-04 01:53 UTC, sethalves commented
The trouble is that I didn't have npm installed, and in tools/CMakeLists.txt :

if (NPM_EXECUTABLE)
  add_subdirectory(jsdoc)
  set_target_properties(jsdoc PROPERTIES FOLDER "Tools")
endif()

so the CMakeLists.txt in jsdoc didn't get processed, and `JSDOC_OUTPUT_PATH` ended up not being set.

2021-07-10 21:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Interface-PR943-99cf0c3-_4152e1ba.dmg

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-99cf0c3-_4152e1ba.dmg

2021-07-11 19:59 UTC, daleglass commented
@sethalves Please retest!

Build is currently failing in the upload script, so ignore that. This version should work both with and without NPM.

2021-07-12 01:03 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Interface-PR943-5358b7b-_276a0506.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-5358b7b-.tar_276a0506.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-5358b7b-_276a0506.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-5358b7b-.tar_276a0506.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-5358b7b-_276a0506.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Quest-Alpha-PR943-5358b7b_276a0506.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-5358b7b_276a0506.apk

2021-07-13 22:32 UTC, ctrlaltdavid commented
Windows builds are failing for me, too: The build locks up in Visual Studio with CPU process still being consumed. I cancel the build and restart the build and it gets a bit further. Repeat a few times and eventually it gets to the end but fails with errors: `error C2065: 'M_PI': undeclared identifier`.

[M_PI errors.txt](https://github.com/vircadia/vircadia/files/6812312/M_PI.errors.txt)

2021-07-17 19:02 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-8ea3263-_32c3725b.dmg

**build (macOS-latest, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-Interface-PR943-8ea3263-_32c3725b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-8ea3263-_32c3725b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-8ea3263-.tar_32c3725b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-8ea3263-.tar_32c3725b.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR943/Vircadia-PR943-8ea3263-_32c3725b.exe

2021-07-17 20:10 UTC, ctrlaltdavid approved these changes

2021-07-22 21:26 UTC, merged