Fix crashes when running with QML disabled in VR
vircadia/vircadia pull request #971
Opened 2021-01-18 21:03 UTC by HifiExperiments

fixes #810 
fixes #811 

Test plan:
- No change to normal builds
- If you build manually with QML disabled, run, and switch to VR, you should no longer crash

2021-01-18 21:04 UTC, HifiExperiments commented on libraries/ui/src/OffscreenUi.cpp
> +    if (_desktop) {
both crashes happens because when QML is disabled, we don't initialize _desktop

2021-01-18 21:04 UTC, HifiExperiments commented on libraries/ui/src/ui/TabletScriptingInterface.cpp
> +#if !defined(DISABLE_QML)
this might not be necessary but doesn't hurt

2021-01-18 22:27 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-fa183fc.tar_4bf95226.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-fa183fc_4bf95226.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-fa183fc.tar_4bf95226.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-fa183fc_4bf95226.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-fa183fc_4bf95226.exe

2021-01-18 23:50 UTC, JulianGro commented
The crash still happens to me:
[vircadia-log.txt](https://github.com/vircadia/vircadia/files/5832803/vircadia-log.txt)

```
(gdb) bt
#0  0x00007fffedfce9c4 in hifi::qml::OffscreenSurface::getRootItem() (this=0x0) at /home/motofckr9k/Vircadia/source/libraries/qml/src/qml/OffscreenSurface.cpp:120
#1  0x00007fffef1a339c in OffscreenUi::isVisible(QString const&) (this=0x0, name=...) at /home/motofckr9k/Vircadia/source/libraries/ui/src/OffscreenUi.cpp:234
#2  0x00007fffef1e713c in TabletProxy::setToolbarMode(bool) (this=0x5555682a64f0, toolbarMode=false) at /home/motofckr9k/Vircadia/source/libraries/ui/src/ui/TabletScriptingInterface.cpp:394
#3  0x00007fffef1e5854 in TabletScriptingInterface::setToolbarMode(bool) (this=0x5555593a4e90, toolbarMode=false) at /home/motofckr9k/Vircadia/source/libraries/ui/src/ui/TabletScriptingInterface.cpp:224
#4  0x0000555555b14390 in Application::updateSystemTabletMode() (this=0x7fffffffacb0) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9453
#5  0x0000555555bcc658 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Application::*)()>::call(void (Application::*)(), Application*, void**) (f=(void (Application::*)(Application * const)) 0x555555b14296 <Application::updateSystemTabletMode()>, o=0x7fffffffacb0, arg=0x7fffffff9e30) at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#6  0x0000555555bbf1ae in QtPrivate::FunctionPointer<void (Application::*)()>::call<QtPrivate::List<>, void>(void (Application::*)(), Application*, void**) (f=(void (Application::*)(Application * const)) 0x555555b14296 <Application::updateSystemTabletMode()>, o=0x7fffffffacb0, arg=0x7fffffff9e30)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#7  0x0000555555ba7bd6 in QtPrivate::QSlotObject<void (Application::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555559717bb0, r=0x7fffffffacb0, a=0x7fffffff9e30, ret=0x0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:414
#8  0x00007fffeadf085f in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#9  0x00005555560ed595 in Application::activeDisplayPluginChanged() (this=0x7fffffffacb0) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/UVLADIE3JM/moc_Application.cpp:1038
#10 0x0000555555b11603 in Application::setDisplayPlugin(std::shared_ptr<DisplayPlugin>) (this=0x7fffffffacb0, newDisplayPlugin=std::shared_ptr<DisplayPlugin> (use count 7, weak count 0) = {...}) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9092
#11 0x0000555555b139fc in Application::setActiveDisplayPlugin(QString const&) (this=0x7fffffffacb0, pluginName=...) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9364
#12 0x0000555555b11b88 in Application::switchDisplayMode() (this=0x7fffffffacb0) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9128
#13 0x00005555560ec54e in Application::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fffffffacb0, _c=QMetaObject::InvokeMetaMethod, _id=131, _a=0x7fffffffa3f0) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/UVLADIE3JM/moc_Application.cpp:815
#14 0x00007fffeadf0745 in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#15 0x00007fffeadfd627 in QTimer::timeout(QTimer::QPrivateSignal) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#16 0x00007fffeadfd988 in QTimer::timerEvent(QTimerEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#17 0x00007fffeadf126b in QObject::event(QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#18 0x00007fffeb8a1e6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#19 0x00007fffeb8a9450 in QApplication::notify(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#20 0x0000555555ae9e4b in Application::notify(QObject*, QEvent*) (this=0x7fffffffacb0, object=0x55555b5c8810, event=0x7fffffffa7e0) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4234
#21 0x00007fffeadc0b48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#22 0x00007fffeae1d0e9 in QTimerInfoList::activateTimers() () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#23 0x00007fffeae1d8e9 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#24 0x00007fffe0f88417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007fffe0f88650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fffe0f886dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007fffeae1dc7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#28 0x00007fffeadbed9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#29 0x00007fffeadc7fa0 in QCoreApplication::exec() () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#30 0x0000555555e00aab in main(int, char const**) (argc=1, argv=0x7fffffffda58) at /home/motofckr9k/Vircadia/source/interface/src/main.cpp:448
(gdb) 
```

2021-01-19 03:45 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.dmg

2021-01-20 04:24 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.dmg

2021-01-20 06:08 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0.tar_3335c040.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-5e592f0_3335c040.dmg

2021-01-20 21:09 UTC, JulianGro commented
It gets further now (I see the world loading and maybe even finish loading in the SteamVR preview window) but still crashes:

[vircadia-log.txt](https://github.com/vircadia/vircadia/files/5845301/vircadia-log.txt)

```
(gdb) bt
#0  0x00007fffef1a3014 in OffscreenUi::isPointOnDesktopWindow(QVariant) (this=0x0, point=...) at /home/motofckr9k/Vircadia/source/libraries/ui/src/OffscreenUi.cpp:213
#1  0x0000555555f517c7 in WindowScriptingInterface::isPointOnDesktopWindow(QVariant) (this=0x5555593ae840, point=...) at /home/motofckr9k/Vircadia/source/interface/src/scripting/WindowScriptingInterface.cpp:204
#2  0x0000555556111d5d in WindowScriptingInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x5555593ae840, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe0f7fb970) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:562
#3  0x00005555561137ab in WindowScriptingInterface::qt_metacall(QMetaObject::Call, int, void**) (this=0x5555593ae840, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe0f7fb970) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:800
#4  0x00007fffec153c8a in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#5  0x00007fffec14d7e7 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#6  0x00007fffec14e27e in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#7  0x00007fffec14e4b2 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#8  0x00007fffec05a028 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#9  0x00007fffec0307f5 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#10 0x00007fff042b6ea0 in  ()
#11 0x00007ffe0f7fbf40 in  ()
#12 0x00007ffe16282e40 in  ()
#13 0x00007ffe00000010 in  ()
#14 0xffff000000000002 in  ()
#15 0x00007ffd00000003 in  ()
#16 0x0000555500000010 in  ()
#17 0x00007ffe0f7fbf60 in  ()
#18 0x0000555555b7ff5c in QSharedPointer<ScriptEngines>::deref() (this=0x7fffec1cbdc8) at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qsharedpointer_impl.h:460
#19 0x00007fffebfe7779 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#20 0x00007fffec082b5d in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#21 0x00007fffec13b919 in QScriptValue::call(QScriptValue const&, QList<QScriptValue> const&) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#22 0x00007ffff4517b76 in ScriptEngine::<lambda()>::operator()(void) const (__closure=0x7ffd84087720) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2785
#23 0x00007ffff451bb14 in std::_Function_handler<void(), ScriptEngine::callWithEnvironment(const EntityItemID&, const QUrl&, QScriptValue, QScriptValue, QScriptValueList)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#24 0x0000555555b486e0 in std::function<void ()>::operator()() const (this=0x7ffe0f7fc2c0) at /usr/include/c++/7/bits/std_function.h:706
#25 0x00007ffff4517a5d in ScriptEngine::doWithEnvironment(EntityItemID const&, QUrl const&, std::function<void ()>) (this=0x55556b24ece0, entityID=..., sandboxURL=..., operation=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2776
#26 0x00007ffff4517c26 in ScriptEngine::callWithEnvironment(EntityItemID const&, QUrl const&, QScriptValue, QScriptValue, QList<QScriptValue>) (this=0x55556b24ece0, entityID=..., sandboxURL=..., function=..., thisObject=..., args=...)
    at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2787
#27 0x00007ffff4508f4d in ScriptEngine::timerFired() (this=0x55556b24ece0) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:1543
#28 0x00007ffff45432ce in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ScriptEngine::*)()>::call(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff4508cdc <ScriptEngine::timerFired()>, o=0x55556b24ece0, arg=0x7ffe0f7fc590)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#29 0x00007ffff453f7b6 in QtPrivate::FunctionPointer<void (ScriptEngine::*)()>::call<QtPrivate::List<>, void>(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff4508cdc <ScriptEngine::timerFired()>, o=0x55556b24ece0, arg=0x7ffe0f7fc590)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#30 0x00007ffff4539f1a in QtPrivate::QSlotObject<void (ScriptEngine::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x7ffd8402ad40, r=0x55556b24ece0, a=0x7ffe0f7fc590, ret=0x0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:414
#31 0x00007fffeadf085f in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#32 0x00007fffeadfd627 in QTimer::timeout(QTimer::QPrivateSignal) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#33 0x00007fffeadfd988 in QTimer::timerEvent(QTimerEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#34 0x00007fffeadf126b in QObject::event(QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#35 0x00007fffeb8a1e6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#36 0x00007fffeb8a9450 in QApplication::notify(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#37 0x0000555555ae9e72 in Application::notify(QObject*, QEvent*) (this=0x7fffffffacc0, object=0x7ffd8402f770, event=0x7ffe0f7fc980) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4237
#38 0x00007fffeadc0b48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#39 0x00007fffeae1d0e9 in QTimerInfoList::activateTimers() () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#40 0x00007fffeae1d8b1 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#41 0x00007fffe0f88417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007fffe0f88650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007fffe0f886dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007fffeae1dc7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#45 0x00007fffeadbed9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#46 0x00007ffff45111d0 in ScriptEngine::include(QStringList const&, QScriptValue) (this=0x55556b24ece0, includeFiles=..., callback=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2112
#47 0x00007ffff451167c in ScriptEngine::include(QString const&, QScriptValue) (this=0x55556b24ece0, includeFile=..., callback=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2126
#48 0x00007ffff458f5ed in ScriptEngine::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x55556b24ece0, _c=QMetaObject::InvokeMetaMethod, _id=45, _a=0x7ffe0f7fd0e0) at /home/moto [...]

2021-01-21 06:49 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-536cea6_2667af36.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-536cea6.tar_2667af36.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-536cea6.tar_2667af36.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-536cea6_2667af36.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-536cea6_2667af36.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Quest-Alpha-PR971-536cea6_2667af36.apk

2021-01-21 15:15 UTC, JulianGro commented
Next crash:

[vircadia-log.txt](https://github.com/vircadia/vircadia/files/5850224/vircadia-log.txt)

```
(gdb) bt
#0  0x00007fffef1a30f4 in OffscreenUi::isPointOnDesktopWindow(QVariant) (this=0x0, point=...) at /home/motofckr9k/Vircadia/source/libraries/ui/src/OffscreenUi.cpp:213
#1  0x0000555555f51969 in WindowScriptingInterface::isPointOnDesktopWindow(QVariant) (this=0x5555593aec00, point=...) at /home/motofckr9k/Vircadia/source/interface/src/scripting/WindowScriptingInterface.cpp:204
#2  0x00005555561121fb in WindowScriptingInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x5555593aec00, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe1dfd7800) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:562
#3  0x0000555556113c49 in WindowScriptingInterface::qt_metacall(QMetaObject::Call, int, void**) (this=0x5555593aec00, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe1dfd7800) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:800
#4  0x00007fffec153c8a in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#5  0x00007fffec14d7e7 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#6  0x00007fffec14e27e in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#7  0x00007fffec14e4b2 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#8  0x00007fffec05a028 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#9  0x00007fffec0307f5 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#10 0x00007fff042b8de0 in  ()
#11 0xbb4900000000870f in  ()
#12 0x00007ffe54808a00 in  ()
#13 0x00007ffe00000010 in  ()
#14 0xffff000000000002 in  ()
#15 0x8549b84500000003 in  ()
#16 0x4800000000000010 in  ()
#17 0x00100842f708508b in  ()
#18 0x00000000850f0000 in  ()
#19 0xffffbb49b8458b49 in  ()
#20 0x00007fff04212470 in  ()
#21 0x00007fffb4434960 in  ()
#22 0x00007ffe57bb9328 in  ()
#23 0x00007ffee8268a88 in  ()
#24 0x00007fffec1cbdc8 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#25 0x00007ffee8267800 in  ()
#26 0x00007ffe57bb9000 in  ()
#27 0x000055556ae73648 in  ()
#28 0x00007ffee8267800 in  ()
#29 0x00007ffe6839b080 in  ()
#30 0x00007fffec1cbdc8 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#31 0x00007fffb4434948 in  ()
#32 0x00007fffebfe7779 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#33 0x00007fffec082b5d in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#34 0x00007fffec13b919 in QScriptValue::call(QScriptValue const&, QList<QScriptValue> const&) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Script.so.5
#35 0x00007ffff4517b76 in ScriptEngine::<lambda()>::operator()(void) const (__closure=0x55556cb14000) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2785
#36 0x00007ffff451bb14 in std::_Function_handler<void(), ScriptEngine::callWithEnvironment(const EntityItemID&, const QUrl&, QScriptValue, QScriptValue, QScriptValueList)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#37 0x0000555555b48760 in std::function<void ()>::operator()() const (this=0x7ffe1dfd8150) at /usr/include/c++/7/bits/std_function.h:706
#38 0x00007ffff4517a5d in ScriptEngine::doWithEnvironment(EntityItemID const&, QUrl const&, std::function<void ()>) (this=0x55556b426880, entityID=..., sandboxURL=..., operation=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2776
#39 0x00007ffff4517c26 in ScriptEngine::callWithEnvironment(EntityItemID const&, QUrl const&, QScriptValue, QScriptValue, QList<QScriptValue>) (this=0x55556b426880, entityID=..., sandboxURL=..., function=..., thisObject=..., args=...)
    at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2787
#40 0x00007ffff4508f4d in ScriptEngine::timerFired() (this=0x55556b426880) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:1543
#41 0x00007ffff45432ce in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ScriptEngine::*)()>::call(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff4508cdc <ScriptEngine::timerFired()>, o=0x55556b426880, arg=0x7ffe1dfd8420)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#42 0x00007ffff453f7b6 in QtPrivate::FunctionPointer<void (ScriptEngine::*)()>::call<QtPrivate::List<>, void>(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff4508cdc <ScriptEngine::timerFired()>, o=0x55556b426880, arg=0x7ffe1dfd8420)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#43 0x00007ffff4539f1a in QtPrivate::QSlotObject<void (ScriptEngine::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x7ffd840299b0, r=0x55556b426880, a=0x7ffe1dfd8420, ret=0x0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:414
#44 0x00007fffeadf085f in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#45 0x00007fffeadfd627 in QTimer::timeout(QTimer::QPrivateSignal) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#46 0x00007fffeadfd988 in QTimer::timerEvent(QTimerEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#47 0x00007fffeadf126b in QObject::event(QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#48 0x00007fffeb8a1e6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#49 0x00007fffeb8a9450 in QApplication::notify(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Widgets.so.5
#50 0x0000555555ae9ef2 in Application::notify(QObject*, QEvent*) (this=0x7fffffffacc0, object=0x7ffd84065650, event=0x7ffe1dfd8810) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4237
#51 0x00007fffeadc0b48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#52 0x00007fffeae1d0e9 in QTimerInfoList::activateTimers() () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#53 0x00007fffeae1d8b1 in  () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#54 0x00007fffe0f88417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007fffe0f88650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007fffe0f886dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007fffeae1dc7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#58 0x00007fffeadbed9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/install_apitraceFix/../qt5-install/lib/libQt5Core.so.5
#59 0x00007ffff45077ad in ScriptEngine::run() (this=0x55556b426880) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:1333
#60 0x00007ffff45432ce in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ScriptEngine::*)()>::call(void (ScriptEngine::*)(), ScriptEngine [...]

2021-01-22 03:01 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52.tar_ff6f7233.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52.tar_ff6f7233.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Quest-Alpha-PR971-d562d52_ff6f7233.apk

2021-01-22 18:44 UTC, JulianGro commented
Green light from me.
The log does get spammed quite a bit with
```
[01/22 19:41:31] [WARNING] [default] DependencyManager::get(): No instance available for 11OffscreenUi
```
 but that should be fixed by https://github.com/vircadia/vircadia/pull/937

2021-01-22 20:03 UTC, ctrlaltdavid commented
Rebuilding now that Qt downloads required for Windows build are working again ...

2021-01-22 21:54 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52.tar_ff6f7233.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52.tar_ff6f7233.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-d562d52_ff6f7233.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Quest-Alpha-PR971-d562d52_ff6f7233.apk

2021-01-23 03:09 UTC, ctrlaltdavid commented
How do you build with QML disabled?
Is it a not uncommon thing to do?

2021-01-23 03:27 UTC, HifiExperiments commented
I would say it’s uncommon.  it’s necessary to do GPU traces via tools like apitrace or nsight, per the related radars.  given that it’s uncommon and that most of this PR just boils down to nullptr checks, I would say this is a low risk change, even though it touches a few files

2021-01-29 21:25 UTC, ctrlaltdavid requested changes

2021-01-29 21:25 UTC, ctrlaltdavid commented on interface/src/ui/InteractiveWindow.cpp
> +        }
```suggestion
        if (auto offscreenUI = DependencyManager::get<OffscreenUi>()) {
            // Build the event bridge and wrapper on the main thread
            offscreenUI->loadInNewContext(CONTENT_WINDOW_QML, objectInitLambda, contextInitLambda);
        }
```

2021-01-29 21:25 UTC, ctrlaltdavid commented on libraries/ui/src/InfoView.cpp
> +        offscreenUI->show(QML, NAME + "_" + path, [=](QQmlContext* context, QObject* newObject){
```suggestion
        offscreenUI->show(QML, NAME + "_" + path, [=] (QQmlContext* context, QObject* newObject) {
```

2021-01-29 21:25 UTC, ctrlaltdavid commented on interface/src/scripting/AssetMappingsScriptingInterface.cpp
> +    if (!offscreenUi) {
```suggestion
    auto offscreenUI = DependencyManager::get<OffscreenUi>();
    if (!offscreenUI) {
```

2021-01-30 08:03 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481.tar_f2c94528.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481_f2c94528.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481.tar_f2c94528.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481_f2c94528.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481_f2c94528.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Quest-Alpha-PR971-a338481_f2c94528.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR971/Vircadia-Alpha-PR971-a338481_f2c94528.apk

2021-02-01 20:20 UTC, ctrlaltdavid approved these changes

2021-02-02 03:17 UTC, digisomni approved these changes
I don't know what a DISABLE_QML build is supposed to fully look like but it didn't crash in desktop or VR on Windows.

2021-02-02 04:16 UTC, JulianGro commented
> I don't know what a DISABLE_QML build is supposed to fully look like but it didn't crash in desktop or VR on Windows.

It won't have any UI elements like the toolbar, apps, settings, etc.

2021-02-02 05:56 UTC, merged