Add onboarding configuration wizard on first run
vircadia/vircadia pull request #999
Opened 2021-02-04 08:09 UTC by digisomni

![image](https://user-images.githubusercontent.com/69767640/106863008-ed295000-6695-11eb-98df-074fa6d56fcc.png)

Give it a go, see how she works and if anything weird/unexpected happens.

If a browser is not supported (such as being on Android) it will give the good ol' QML dialog box asking you for a name.

The main benefit to this is that I can add in literally any configuration options/tutorial info/anything we want to ask/tell/set at a later date.... That'll be very important in tying down configurations and system requirements back to where they should be (much lower than where they are now!)

2021-02-04 08:47 UTC, digisomni commented
Oh, and I modified the away script to trigger from a 3rd party script instead of itself, that way the "ESC" functionality can be expanded later.

2021-02-04 09:46 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd.tar_4d701156.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd.tar_4d701156.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd_4d701156.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd_4d701156.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd_4d701156.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd_4d701156.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Quest-Alpha-PR999-57ab4dd_4d701156.apk

2021-02-18 22:11 UTC, SilverfishVR commented
Testing [PR999-57ab4dd](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Alpha-PR999-57ab4dd_4d701156.exe)

It does not trigger for me by default, the only way I could make it run was to manually load `onFirstRun.js ` and then set `"firstRun": true` in interface.json

* position is wack, it's floating off the platform:
![Screenshot 2021-02-18 22 31 20](https://user-images.githubusercontent.com/53531160/108425527-dc064480-723a-11eb-9a4d-fa2d5485990d.png)

* the defaults are lowest tier possible, especially the forced low framerate makes for a very bad experience if you just click through it.

* the "performance" tab should make clear what it does by listing the target framerates.

* not all tabs/pages are the same size, OCD trigger 😄 

* instead of a one-shot run, it could be a permanent panel in the serverless with a "rerun" button at the end.

* in the future, stuff like audio setup, avatar selection etc. could be added.

2021-02-19 12:45 UTC, digisomni commented
All done, it's ready to test again! :)

2021-02-19 14:37 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f_8d8c141d.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f.tar_8d8c141d.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f.tar_8d8c141d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f_8d8c141d.sh

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f_8d8c141d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Quest-Alpha-PR999-08d015f_8d8c141d.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f_8d8c141d.exe

2021-02-20 19:01 UTC, SilverfishVR commented
Testing [PR999-08d015f](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-08d015f_8d8c141d.exe)

looks good, only issue now is that is spawns right in front of the controls guide, we should update the serverless to move that one (and redo it in appropriate style)

2021-02-21 00:10 UTC, Aitolda commented
Issue:
In VR mode the Performance card means nothing as your framerate will always be set to real-time.  My first thought was just have it say "affects desktop only" or something like this, however... if you were in VR when you made this selection, it is ignored anyway and won't even impact desktop if you switch back.  Not really sure what the solution is atm.

2021-02-21 00:12 UTC, digisomni commented
Is it actually the case that setting your refresh rate profile while in VR will not be counted when switching back to desktop? That sounds a bit like a bug... it should be setting the setting no matter what, no?

2021-02-21 01:23 UTC, Aitolda commented
> Is it actually the case that setting your refresh rate profile while in VR will not be counted when switching back to desktop? That sounds a bit like a bug... it should be setting the setting no matter what, no?

Back on stable if I change the refresh rate while in VR it definitely impacts desktop when I switch back.

2021-02-21 01:26 UTC, digisomni commented
And doing that in this PR doesn't work...? Even if you use the tablet graphics settings?

2021-02-21 01:43 UTC, Aitolda commented
> And doing that in this PR doesn't work...? Even if you use the tablet graphics settings?

Works in the PR too, but not through the tutorial. Only in the graphics tab.

2021-02-23 20:35 UTC, ctrlaltdavid requested changes

2021-02-23 20:35 UTC, ctrlaltdavid commented on interface/resources/serverless/tutorial.json
> +      "id": "{0a199807-4a83-4286-b09c-f21124627c3e}",
Indentation appears to be off.

2021-02-23 20:35 UTC, ctrlaltdavid commented on scripts/system/away.js
>  //  Copyright 2015 High Fidelity, Inc.
```suggestion
//  Copyright 2015 High Fidelity, Inc.
//  Copyright 2021 Vircadia contributors.
```

2021-02-23 20:35 UTC, ctrlaltdavid commented on scripts/system/away.js
> +            setEnabled(message === 'enable');
```suggestion
            setEnabled(true);
```

2021-02-23 20:35 UTC, ctrlaltdavid commented on scripts/system/onEscape.js
> +//  Copyright 2020 Vircadia contributors.
```suggestion
//  Copyright 2021 Vircadia contributors.
```

2021-02-25 23:15 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-37bb6c3_9b2c6d88.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-37bb6c3.tar_9b2c6d88.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-37bb6c3.tar_9b2c6d88.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-37bb6c3_9b2c6d88.dmg

2021-02-26 00:29 UTC, digisomni commented
I tested this with a Valve Index and could not reproduce the issue. Even so, it's quite the edge case so I'm not worried about something like that happening for now. If you have a VR setup then you'll likely know how to double check your graphics settings if things were weird with the Graphics menu.

This wizard is meant to assist the most technically challenged, especially people who are not invested in the platform but are rather here to attend an event or something of the sort.

2021-02-26 00:38 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861-.tar_75dad297.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861-_75dad297.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861-.tar_75dad297.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861-_75dad297.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861-_75dad297.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-PR999-121f861_75dad297.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR999/Vircadia-Quest-Alpha-PR999-121f861_75dad297.apk

2021-02-26 01:08 UTC, ctrlaltdavid approved these changes

2021-02-26 01:49 UTC, merged